city:
  service:
    url: http://localhost:3030/open-city-api

spring:
  #redis:
  #  username: sam
  #  password: pass123
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres